{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "auth-stack.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth-stack.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-stack.backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
        env:
        - name: NODE_ENV
          value: {{ .Values.backend.env.NODE_ENV | quote }}
        - name: PORT
          value: {{ .Values.backend.env.PORT | quote }}
        - name: DB_HOST
          value: {{ .Values.backend.env.DB_HOST | quote }}
        - name: DB_USER
          value: {{ .Values.backend.env.DB_USER | quote }}
        - name: DB_NAME
          value: {{ .Values.backend.env.DB_NAME | quote }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: root-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        livenessProbe:
          {{- toYaml .Values.backend.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.backend.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
      initContainers:
      - name: wait-for-db
        image: busybox:1.35
        command: ['sh', '-c']
        args:
          - |
            echo "Waiting for MariaDB to be ready..."
            until nc -z mariadb-service {{ .Values.mariadb.service.port }}; do
              echo "Waiting for MariaDB..."
              sleep 2
            done
            echo "MariaDB is ready!"
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
