{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "auth-stack.mariadb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mariadb.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth-stack.mariadb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-stack.mariadb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
        imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mariadb.service.targetPort }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        {{- if .Values.configMap.enabled }}
        - name: mariadb-init
          mountPath: /docker-entrypoint-initdb.d
        {{- end }}
        livenessProbe:
          {{- toYaml .Values.mariadb.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.mariadb.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.mariadb.resources | nindent 10 }}
      volumes:
      {{- if .Values.mariadb.persistence.enabled }}
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
      {{- else }}
      - name: mariadb-storage
        emptyDir: {}
      {{- end }}
      {{- if .Values.configMap.enabled }}
      - name: mariadb-init
        configMap:
          name: mariadb-init-config
      {{- end }}
      {{- with .Values.mariadb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
