{{- if and .Values.mariadb.enabled .Values.mariadb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "auth-stack.mariadb.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mariadb.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
  {{- if .Values.mariadb.persistence.storageClass }}
  {{- if (eq "-" .Values.mariadb.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.mariadb.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}
