apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-stack
  namespace: argocd
  labels:
    app: auth-stack
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Source configuration
  source:
    repoURL: https://github.com/chingnokas/vendor2025-app.git
    targetRevision: main
    path: helm/auth-stack
    helm:
      # Helm-specific configuration
      valueFiles:
        - values.yaml
      parameters:
        - name: frontend.image.repository
          value: ghcr.io/chingnokas/vendor2025-app/frontend
        - name: backend.image.repository
          value: ghcr.io/chingnokas/vendor2025-app/backend
        - name: frontend.image.tag
          value: latest
        - name: backend.image.tag
          value: latest
      # Override values for production
      values: |
        global:
          imageRegistry: ghcr.io
        
        frontend:
          replicaCount: 3
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
        
        backend:
          replicaCount: 3
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          secrets:
            jwtSecret: "production-jwt-secret-change-me"
        
        mariadb:
          auth:
            rootPassword: "secure-production-password"
          persistence:
            size: 20Gi
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
        
        ingress:
          enabled: true
          hosts:
            - host: auth.yourdomain.com
              paths:
                - path: /
                  pathType: Prefix
                  service: frontend-service
                  port: 8080
                - path: /api
                  pathType: Prefix
                  service: backend-service
                  port: 3000
          tls:
            - secretName: auth-tls
              hosts:
                - auth.yourdomain.com

  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-app

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health and sync configuration
  revisionHistoryLimit: 10
  
  # Ignore differences for certain fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      jsonPointers:
        - /data

  # Info section
  info:
    - name: Description
      value: Authentication Stack with Angular, Express.js, and MariaDB
    - name: Repository
      value: https://github.com/chingnokas/vendor2025-app
    - name: Maintainer
      value: Lyndon (chingnokas)
