apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-stack-frontend
  namespace: argocd
  labels:
    app: auth-stack-frontend
    component: frontend
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    # Refresh every 30 seconds to quickly detect frontend changes
    argocd.argoproj.io/refresh: "30s"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Source configuration - Monitor repository for frontend changes
  source:
    repoURL: https://github.com/chingnokas/vendor2025-app.git
    targetRevision: main
    path: helm/auth-stack
    helm:
      valueFiles:
        - values.yaml
      # Override values specifically for frontend deployment
      values: |
        # Enable only frontend component
        frontend:
          enabled: true
          replicaCount: 3
          image:
            repository: ghcr.io/chingnokas/vendor2025-app/frontend
            tag: latest
            pullPolicy: Always
          service:
            type: LoadBalancer
            port: 8080
            targetPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
        
        # Keep backend and database for full stack
        backend:
          enabled: true
          replicaCount: 2
          image:
            repository: chingnokas/b-app
            tag: latest
            pullPolicy: IfNotPresent
        
        mariadb:
          enabled: true
          replicaCount: 1
          persistence:
            enabled: true
            size: 10Gi
        
        # Ingress configuration
        ingress:
          enabled: true
          hosts:
            - host: auth-app.local
              paths:
                - path: /
                  pathType: Prefix
                  service: frontend-service
                  port: 8080
                - path: /api
                  pathType: Prefix
                  service: backend-service
                  port: 3000

  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-app

  # Automated sync policy for frontend changes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  # Health and sync configuration
  revisionHistoryLimit: 10
  
  # Ignore differences for dynamic fields
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: frontend-deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs

  # Info section
  info:
    - name: Description
      value: Frontend component of Authentication Stack - Auto-deploys on frontend changes
    - name: Repository
      value: https://github.com/chingnokas/vendor2025-app
    - name: Component
      value: Angular Frontend
    - name: Auto-Sync
      value: Enabled for frontend changes
    - name: Maintainer
      value: Lyndon (chingnokas)
